### ISSUE TITLE
Flatten dir structure for compatibility with given Makefile

### ISSUE THREAD

**Issue by akvashi24** [DTxCode/SWDev-A1-Part2#14]
The structure as it is now doesn't jive well with the instructors' Makefille.  [PR](https://github.com/DTxCode/SWDev-A1-Part2/pull/13) submitted if you guys just wanna merge.

**Comment by DTxCode** [comment]
Hey guys, we could do this but we don't want to mess with other teams using our repo.
All you need is this:
In the line under `third:`
```
cd ./part1; cp array.h queue.h map.h string.h object.h Makefile  ./test-map
```
change to
```
cd ./part1; cp array.h queue.h map.h string.h object.h Makefile ./test-map/part2
```

And then change
```
- docker run -ti -v `pwd`:/test cs4500:0.1 bash -c "cd /test/part1/test-map ; make testMap"
```
to
```
- docker run -ti -v `pwd`:/test cs4500:0.1 bash -c "cd /test/part1/test-map/part2 ; make testMap"
```


Let us know if that works. Thanks,

**Comment by akvashi24** [comment]
Fair enough.  It wasn't too bad a fix.  Thanks for your tips!
