### ISSUE TITLE
Test Bug

### ISSUE THREAD

**Issue by seanolly** [DTxCode/SWDev-A1-Part2#15]
https://github.com/DTxCode/SWDev-A1-Part2/blob/1399ab3ebb7ec05368f5d8f997621c5688c5d51b/part2/test-map.cpp#L118

The interface for put: "// Associates the given key with the given value. Any existing value
    // associated with this key is overwritten", however, in this test, a key k, and value v are put(k, v) into the map, then a call put(k, nullptr) is made. The assertion in the test expects v to still be in the map, but this is contradictory to what the method behavior statement says.

**Comment by DTxCode** [comment]
The method also includes the purpose statement:
`    // Does nothing if key or value == nullptr`

I believe that's what that's testing - that putting nullptr did nothing.
Let me know if that clears it up.

**Comment by seanolly** [comment]
thanks for clearing that up. I think I was on an old commit where that last line in comments must've been accidentally deleted on our end...
