### ISSUE TITLE
lowercase repo

### ISSUE THREAD

**Issue by seanolly** [DTxCode/SWDev-A1-Part2#17]
Having issues running this with given Dockerfile, one of the specifications was that your repo was to be all lowercase

**Comment by DTxCode** [comment]
Hey guys, this isn't referring to the Github repo name. I believe it means you have a space in your pwd path.

See:
https://piazza.com/class/k51bluky59n2jr?cid=373
https://stackoverflow.com/questions/48522615/docker-error-invalid-reference-format-repository-name-must-be-lowercase
