### ISSUE TITLE
Map API Change Request

### ISSUE THREAD

**Issue by seanolly** [DTxCode/SWDev-A1-Part2#2]
According to the A2 spec, it looks like we need an API to support not only String to Object mappings, but Object to Object mappings. Could you alter your tests and interface to support this?

From the site:
"Lastly, your Map should support mapping Strings to Strings and generally Object to Object. The performance of the Map class should be tuned to avoid pathological cases by rehashing when the load gets too high. Aim for fast code, whatever that means."

**Comment by DTxCode** [comment]
Fixed! Let us know if there are any other issues. Thanks.
