### ISSUE TITLE
Test Request

### ISSUE THREAD

**Issue by seanolly** [DTxCode/SWDev-A1-Part2#5]
Hi, one last thing,
we have our map resizing, and rehashing for efficiency purposes if the # of unique elements inserted is >= 1/4 the internal array capacity.
I suggest that this should be tested, to make it easier, you should define an alternate constructor for map that takes in a capacity that overrides our default.

Let me know if you have any questions, but all in all, thanks for being very responsive to our requests.
From Sean, and Max

**Comment by DTxCode** [comment]
Hey guys, this one we have to disagree with. 

Capacity management is an implementation detail that we don't think should be reflected in the spec. The spec (and constructors for that matter) are for the end user of your array who "shouldn't" have to care about capacity. Creating a constructor for tests is similarly bad design in our opinion.

Then again, I'm not sure how you guys would test your code without writing some tests yourself given your knowledge of when your capacity resizes. Maybe ask on piazza about this one?

**Comment by seanolly** [comment]
Ok, we agree with than rationale.
Thanks
