### ISSUE TITLE
New String interface

### ISSUE THREAD

**Issue by sg126** [DTxCode/SWDev-A1-Part2#6]
Can you please change your string.h and object.h to the ones in the discussion in this post?
https://piazza.com/class/k51bluky59n2jr?cid=330 it would make it standardized for all of the data structures.

**Comment by DTxCode** [comment]
Hey guys, based on https://piazza.com/class/k51bluky59n2jr?cid=314 we think you're allowed to change string.h and object.h to whatever you like. I took a look at our tests and I think if you changed yours to the ones on piazza it should still pass our spec. Let us know if you think otherwise.

**Comment by sg126** [comment]
Hey, thanks for responding to this! We will test it out!
