### ISSUE TITLE
Use the Google Test framework for tests

### ISSUE THREAD

**Issue by gyroknight** [DTxCode/SWDev-A1-Part2#7]
I'd suggest rewriting your tests to use the Google Test framework for more flexibility.

**Comment by DTxCode** [comment]
While the Google framework looks good in general, we don't think it's necessary for this assignment. We also don't want to force other groups that have our spec to have to change their versions as well.  In the future we're more likely to start off using that framework.
Let us know if there's something else about our spec that needs fixing.
